pipeline {
	agent any
	stages {

		stage('Create kubernetes cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'awslogin') {
					sh '''
						eksctl create cluster \
						--name mycluster \
						--version 1.17 \
						--nodegroup-name workers \
						--node-type t2.micro \
						--nodes 3 \
						--nodes-min 1 \
						--nodes-max 4 \
						--node-ami auto \
						--region us-east-1 \
						--zones us-east-1a \
						--zones us-east-1b \
						--zones us-east-1c \
						--zones us-east-1d \
					'''
				}
			}
		}

		

		stage('Create conf file cluster') {
			steps {
				withAWS(region:'us-east-1', credentials:'awslogin') {
					sh '''
						aws eks --region us-east-1 update-kubeconfig --name mycluster
					'''
				}
			}
		}

	}
}
