apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 50%
        maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          imagePullPolicy: Always
          image: IMAGE
          ports:
            - containerPort: 3000
          readinessProbe:
              httpGet:
                path: /
                port: 3000
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 10